version: '2'

services:
  project:
    image: crowdcomms/django-test:latest
    build: .
    command:
      "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app/
